Add a QQ provider
aspnet-contrib/AspNet.Security.OAuth.Providers pull request #160
Opened 2017-05-23 03:40 UTC by zhengchun

#138 
Test successful

2017-07-26 00:23 UTC, kevinchalet requested changes

2017-07-26 00:23 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.QQ/QQAuthenticationHandler.cs
> +                {"oauth_consumer_key",Options.ClientId },
`oauth_consumer_key` is an OAuth1 thing. Are you sure QQ supports OAuth2?

2017-07-26 00:23 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.QQ/QQAuthenticationHandler.cs
> +                    .AddOptionalClaim("urn:qq:figureurl_1", QQAuthenticationHelper.GetFigureUrl1(payload), Options.ClaimsIssuer)
Not sure I like these _1/_2/qq_1/qq_2 claims. Do we really need them? What do they do?

2017-07-26 00:23 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.QQ/QQAuthenticationHandler.cs
> +            var i = body.IndexOf("{");
That sounds fragile. What's the purpose of this thing?

2017-07-26 00:23 UTC, PinpointTownes commented
@zhengchun thanks for your PR (and sorry for the late review).

I added a few remarks, but overall it looks good.

2017-07-26 09:54 UTC, zhengchun commented on src/AspNet.Security.OAuth.QQ/QQAuthenticationHandler.cs
> +                {"oauth_consumer_key",Options.ClientId },
yes, QQ supports OAuth2.

2017-07-26 10:50 UTC, zhengchun commented on src/AspNet.Security.OAuth.QQ/QQAuthenticationHandler.cs
> +            var i = body.IndexOf("{");
The QQ OAuth server responses openid content format like this: `callback( {“client_id”:”YOUR_APPID”,”openid”:”YOUR_OPENID”} );`

2017-07-26 11:25 UTC, zhengchun commented on src/AspNet.Security.OAuth.QQ/QQAuthenticationHandler.cs
> +                    .AddOptionalClaim("urn:qq:figureurl_1", QQAuthenticationHelper.GetFigureUrl1(payload), Options.ClaimsIssuer)
Sorry, its my fault, I'm add new commit.

2017-10-02 11:44 UTC, PinpointTownes commented
Merged: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/c8c923a5b6149fa7693bd3a54bbcbc988fc1a56e

Thanks for your contribution :+1:

2017-10-02 11:44 UTC, closed without merging