Add an Odnoklassniki provider
aspnet-contrib/AspNet.Security.OAuth.Providers pull request #163
Opened 2017-06-18 15:02 UTC by Vertigo093i

* https://ok.ru/
* [Server OAuth authorization](https://apiok.ru/en/ext/oauth/server)

2017-07-26 00:26 UTC, kevinchalet requested changes

2017-07-26 00:26 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationExtensions.cs
> +        public static IApplicationBuilder UseOdnoklassnikiAuthentication(
Can you please add the XML docs? You can copy/paste them from another provider.

2017-07-26 00:26 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationHandler.cs
> +            var args = new Dictionary<string, string>
Please consider moving that to a separate private/protected method like what we do in the other providers that require this stupid signing thing.

2017-07-26 00:26 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationOptions.cs
> +        public string ClientPublic { get; set; }
XML docs? Also, not sure the name is descriptive enough. What does this property do?

2017-07-26 00:27 UTC, PinpointTownes commented
@Vertigo093i thanks for your PR (and sorry for the late review :sweat:)

I added a few remarks, but overall it looks good :+1:

2017-07-26 00:29 UTC, PinpointTownes commented
@Vertigo093i I don't see the ugly signing part mentioned in the https://apiok.ru/en/ext/oauth/server document. Is it really a mandatory thing or just something optional?

2017-07-27 11:08 UTC, Vertigo093i commented
Yes, the signing is mandatory for API calls. Have a look at https://apiok.ru/en/dev/methods/.

2017-07-27 13:50 UTC, Vertigo093i commented on src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationHandler.cs
> +            var args = new Dictionary<string, string>
OK. Found such thing in the Instagram provider.

2017-07-27 13:58 UTC, Vertigo093i commented on src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationOptions.cs
> +        public string ClientPublic { get; set; }
Well, this one is another (besides `ClientId` and `ClientSecret`) parameter of an application. It is referred to as "application public key". I've named the property this way to be consistent with the other properties. I'm leaving it unchanged for now (only adding docs). Let me know if you require it to be named differently. May be `PublicKey` or `AppPublic`. Or even `AppPublicKey`.

2017-07-27 14:22 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationOptions.cs
> +        public string ClientPublic { get; set; }
`ClientPublic` is confusing as it makes me think that it's a flag used to determine whether the client app is a confidential or public app (which is absolutely not what it does).

Consider renaming it to `ApplicationKey` (it's the name I've used for the OpenID2 Steam provider: https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/dev/src/AspNet.Security.OpenId.Steam/SteamAuthenticationOptions.cs#L25)

2017-07-27 15:05 UTC, Vertigo093i commented on src/AspNet.Security.OAuth.Odnoklassniki/OdnoklassnikiAuthenticationOptions.cs
> +        public string ClientPublic { get; set; }
/// <summary>
        /// Gets or sets the application key used to retrieve user details from Odnoklassniki's API.
        /// </summary>
        public string ApplicationKey { get; set; }

Good enough?

2017-09-11 17:04 UTC, Vertigo093i commented
@PinpointTownes Would you like to merge this PR?

2017-10-02 11:02 UTC, PinpointTownes commented
> @PinpointTownes Would you like to merge this PR?

Yep. Could you please squash your PR into a single commit? Thanks.

2017-10-02 13:29 UTC, Vertigo093i commented
No, I can't. Since you requested some changes and they were made as part of
this PR. That's how they work.

On Oct 2, 2017 14:02, "Kévin Chalet" <notifications@github.com> wrote:

> @PinpointTownes <https://github.com/pinpointtownes> Would you like to
> merge this PR?
>
> Yep. Could you please squash your PR into a single commit? Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/163#issuecomment-333503515>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AC3f3snheN61OxSf7OvkXAo4L8mUzYuyks5soMLXgaJpZM4N9hMj>
> .
>

2017-10-02 13:36 UTC, PinpointTownes commented
Not sure I understand what prevents you from rebasing your PR on top of the `dev` branch and squashing all your commits into a single one. All the contributors before you have been requested to do something similar. That said, if you prefer, we can simply close the PR.

2017-10-02 13:40 UTC, closed without merging