Migrate some provider to ASP.NET Core 2.0
aspnet-contrib/AspNet.Security.OAuth.Providers pull request #173
Opened 2017-09-20 06:33 UTC by kinosang

Port providers to the new ASP.NET Core 2.0 authentication stack:
* [ ] Migrate the Dropbox provider to ASP.NET Core 2.0
* [ ] Migrate the Paypal provider to ASP.NET Core 2.0
* [ ] Migrate the Reddit provider to ASP.NET Core 2.0
* [ ] Migrate the Weixin provider to ASP.NET Core 2.0
* [ ] Migrate the Yahoo provider to ASP.NET Core 2.0
* [x] Migrate the Weibo provider to ASP.NET Core 2.0

New providers:
* [ ] Add the Baidu provider for ASP.NET Core 2.0
* [ ] Add the QQ provider for ASP.NET Core 2.0

Or should I create another pr for the new providers?

2017-09-20 06:45 UTC, huww98 commented
I want to add the QQ provider for ASP.NET Core 2.0 based on #160. Maybe I will create a PR today.

2017-10-02 10:17 UTC, PinpointTownes commented
Awesome, thanks! Could you please squash the intermediate commits to only have the `Migrate XYZ` ones?

2017-10-02 10:30 UTC, kinosang commented
@PinpointTownes I'll do it asap.

2017-10-03 01:23 UTC, kinosang commented
@PinpointTownes all done.

2017-10-03 17:23 UTC, kevinchalet requested changes

2017-10-03 17:23 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.ArcGIS/ArcGISAuthenticationHandler.cs
> +                throw new HttpRequestException("An error occurred while retrieving user information.");
Any particular reason to change the error message?

2017-10-03 17:23 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Paypal/PaypalAuthenticationHandler.cs
> +            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, payload.Value<string>("user_id")?.Split('/')?.LastOrDefault(), ClaimValueTypes.String, Options.ClaimsIssuer));
FYI, you can use `ClaimActions.MapCustomJson` to add claims contained in nested JSON objects. E.g: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/MicrosoftAccountOptions.cs#L32

Any chance we could use it everywhere we can?

2017-10-03 17:23 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Vimeo/VimeoAuthenticationHandler.cs
> +            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, payload.Value<string>("uri")?.Split('/')?.LastOrDefault(), ClaimValueTypes.String, Options.ClaimsIssuer));
Same remark (I see this pattern in a few places, that would be cool to move to the claims actions API).

2017-10-03 17:23 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Weibo/WeiboAuthenticationHandler.cs
> +            // When the email address is not public, retrieve it from
I'm not against adding that, but not as part of this PR. Please remove it temporarily from the associated commit and open a new ticket to bring it back in both the ASP.NET Core 1.0 and 2.0 versions.

2017-10-03 17:24 UTC, PinpointTownes commented
@kinosang thank you very much. I added a few remarks but overall it looks great. Please ping me when they are addressed and I'll merge your PR ASAP.

2017-10-03 18:11 UTC, kinosang commented
@PinpointTownes done, waiting for CI testing.

2017-10-05 13:53 UTC, kinosang commented
syn @PinpointTownes

2017-10-08 05:35 UTC, kinosang commented
ping @PinpointTownes

2017-10-27 14:13 UTC, kevinchalet approved these changes

2017-10-27 14:13 UTC, PinpointTownes commented
@kinosang sorry for the long delay, I was busy with tons of other things.

I just merged your PR. Thank you very much for your effort, it's much appreciated! :clap:

2017-10-27 14:13 UTC, closed without merging