Spotify Provider to ASP.NET Core 2.0
aspnet-contrib/AspNet.Security.OAuth.Providers pull request #178
Opened 2017-09-20 20:20 UTC by 0xNF

Migrate the Spotify provider to ASP.NET Core 2.0

2017-09-23 13:05 UTC, TheUltimateC0der approved these changes

2017-10-02 10:28 UTC, PinpointTownes commented
Thanks for your PR. I took a brief look and I see many inconsistencies with the other providers (e.g we don't want to add the claims using the events model as the default logic would be lost if the users provided their own delegates).

Please fix the inconsistencies (including styling differences) and squash your PR.

2017-10-03 17:45 UTC, kevinchalet requested changes

2017-10-03 17:45 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Spotify/AspNet.Security.OAuth.Spotify.csproj
> -  <PropertyGroup>
Remove the format change please.

2017-10-03 17:45 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Spotify/AspNet.Security.OAuth.Spotify.csproj
> +    <Authors>Adam Reisinger; 0xNF</Authors>
Remove the extra space.

2017-10-03 17:45 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Spotify/SpotifyAuthenticationExtensions.cs
> +
Remove.

2017-10-03 17:45 UTC, PinpointTownes commented on src/AspNet.Security.OAuth.Spotify/SpotifyAuthenticationOptions.cs
> +        public SpotifyAuthenticationOptions()
Remove the extra space, please.

2017-10-03 17:45 UTC, PinpointTownes commented
Minor a few remarks, it looks fine.

When you're done, please rebase and squash your PR into a single commit named `Migrate the Spotify provider to ASP.NET Core 2.0` :+1:

2017-10-04 12:53 UTC, 0xNF commented
Sure - I'll get the changes done within the day.

2017-11-01 18:26 UTC, PinpointTownes commented
Merged, thanks for your contribution @0xNF! :clap: 

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/commit/356d626ad6713c49d81e1e92f0d16c68657ce955

2017-11-01 18:26 UTC, closed without merging