FIX Twitch Provider in 1.0
aspnet-contrib/AspNet.Security.OAuth.Providers pull request #244
Opened 2018-06-09 14:22 UTC by zAfLu

See #242

2018-06-09 22:36 UTC, kinosang commented on src/AspNet.Security.OAuth.Twitch/AspNet.Security.OAuth.Twitch.csproj
> +  <ItemGroup>
remove this, keep the csproj file clear

2018-06-09 22:39 UTC, kinosang requested changes

2018-06-09 22:39 UTC, kinosang commented on src/AspNet.Security.OAuth.Twitch/AspNet.Security.OAuth.Twitch.csproj
> +  <ItemGroup>
remove this, keep the csproj file clear

2018-06-10 02:22 UTC, zAfLu commented on src/AspNet.Security.OAuth.Twitch/AspNet.Security.OAuth.Twitch.csproj
> +  <ItemGroup>
Should be removed now

2018-06-14 14:22 UTC, PinpointTownes commented
Merged, thanks for your contribution :+1:

2018-06-14 14:22 UTC, closed without merging