Add NetEase provider
aspnet-contrib/AspNet.Security.OAuth.Providers pull request #389
Opened 2020-02-23 06:44 UTC by HahaMango

Hi, I implemented a NetEase provider, also add the test code.

Hot to use:

```csharp
builder.AddNetEase(options => 
{
    options.ClientId = "your client Id ";
    options.ClientSecret = "your client secret ";
});
```

2020-02-23 16:45 UTC, martincostello requested changes
As an OAuth provider, HTTPS needs to be used everywhere.

2020-02-23 16:45 UTC, martincostello commented on README.md
> +|  NetEase  | [![NuGet](https://buildstats.info/nuget/AspNet.Security.OAuth.NetEase?includePreReleases=false)](https://www.nuget.org/packages/AspNet.Security.OAuth.NetEase/ "Download AspNet.Security.
```suggestion
| NetEase | [![NuGet](https://buildstats.info/nuget/AspNet.Security.OAuth.NetEase?includePreReleases=false)](https://www.nuget.org/packages/AspNet.Security.OAuth.NetEase/ "Download AspNet.Security.OAuth.NetEase from NuGet.org") |  [![MyGet](https://buildstats.info/myget/aspnet-contrib/AspNet.Security.OAuth.NetEase?includePreReleases=false)](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OAuth.NetEase "Download AspNet.Security.OAuth.NetEase from MyGet.org") |  [Documentation](https://reg.163.com/help/help_oauth2.html "NetEase developer documentation") |
```

2020-02-23 16:45 UTC, martincostello commented on src/AspNet.Security.OAuth.NetEase/NetEaseAuthenticationDefaults.cs
> +        public const string AuthorizationEndpoint = "http://reg.163.com/open/oauth2/authorize.do";
```suggestion
        public const string AuthorizationEndpoint = "https://reg.163.com/open/oauth2/authorize.do";
```

2020-02-23 16:45 UTC, martincostello commented on src/AspNet.Security.OAuth.NetEase/NetEaseAuthenticationDefaults.cs
> +        public const string TokenEndpoint = "http://reg.163.com/open/oauth2/token.do";
```suggestion
        public const string TokenEndpoint = "https://reg.163.com/open/oauth2/token.do";
```

2020-02-23 16:45 UTC, martincostello commented on src/AspNet.Security.OAuth.NetEase/NetEaseAuthenticationOptions.cs
> +            ClaimActions.MapJsonKey(ClaimTypes.Name, "username");
User name isn't really a name if it's also an email address.

2020-02-23 16:45 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/NetEase/NetEaseTests.cs
> +        [InlineData(ClaimTypes.Email, "urstest_mreg")]
This doesn't look like an email address?

2020-02-23 16:45 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/NetEase/bundle.json
> +      "uri": "http://reg.163.com/open/oauth2/token.do",
```suggestion
      "uri": "https://reg.163.com/open/oauth2/token.do",
```

2020-02-23 16:45 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/NetEase/bundle.json
> +      "comment": "http://reg.163.com/help/help_oauth2.html",
```suggestion
      "comment": "https://reg.163.com/help/help_oauth2.html",
```

2020-02-23 16:45 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/NetEase/bundle.json
> +      "comment": "See http://reg.163.com/help/help_oauth2.html",
```suggestion
      "comment": "See https://reg.163.com/help/help_oauth2.html",
```

2020-02-23 16:45 UTC, martincostello commented on src/AspNet.Security.OAuth.NetEase/NetEaseAuthenticationOptions.cs
> +            ClaimActions.MapJsonKey(ClaimTypes.Email, "username");
The user name, at least in the sample in the docs, isn't an email address.

2020-02-24 09:39 UTC, HahaMango commented
@martincostello Yes, according to the document it's just a user name, not a mailbox, my fault. I've changed it.

2020-02-24 09:52 UTC, martincostello approved these changes

2020-02-24 09:52 UTC, merged

2020-02-24 09:52 UTC, martincostello commented
Thanks again for your contribution @HahaMango 🎉

2020-04-20 18:09 UTC, martincostello commented
This provider is now available from NuGet.org: https://www.nuget.org/packages/AspNet.Security.OAuth.NetEase/3.1.0