For #544. Add Coinbase provider
aspnet-contrib/AspNet.Security.OAuth.Providers pull request #551
Opened 2021-05-24 23:53 UTC by levimatheri

Add Coinbase provider

2021-05-25 17:28 UTC, martincostello commented on AspNet.Security.OAuth.Coinbase/CoinbaseAuthenticationDefaults.cs
> +        public const string TokenEndpoint = "http://www.coinbase.com/oauth/token";
```suggestion
        public const string TokenEndpoint = "https://www.coinbase.com/oauth/token";
```

2021-05-25 17:28 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/AspNet.Security.OAuth.Providers.Tests.csproj
> +
This isn't needed.

```suggestion
```

2021-05-25 17:28 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/AspNet.Security.OAuth.Providers.Tests.csproj
> +
This isn't needed.

```suggestion
```

2021-05-25 17:28 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/Coinbase/bundle.json
> +      "uri": "http://www.coinbase.com/oauth/token",
```suggestion
      "uri": "https://www.coinbase.com/oauth/token",
```

2021-05-30 00:52 UTC, levimatheri commented
@martincostello Thank you for reviewing! I've updated the branch with the changes. Thanks.

2021-06-01 07:20 UTC, martincostello requested changes
The whole `AspNet.Security.OAuth.Coinbase` directory needs moving into the `src` directory.

2021-06-01 07:22 UTC, martincostello commented on AspNet.Security.OAuth.Coinbase/CoinbaseAuthenticationExtensions.cs
> +        /// Adds <see cref="DropboxAuthenticationHandler"/> to the specified
```suggestion
        /// Adds <see cref="CoinbaseAuthenticationHandler"/> to the specified
```

2021-06-01 07:22 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/AspNet.Security.OAuth.Providers.Tests.csproj
> +
```suggestion

```

2021-06-01 23:32 UTC, levimatheri commented
@martincostello Sorry about that. Moved to `src\` directory. Thanks.

2021-06-02 07:25 UTC, martincostello reviewed
One minor change and then this looks good to go.

2021-06-02 07:25 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/Coinbase/CoinbaseTests.cs
> +        [Theory]
Just noticed there's no test case for the email claim.

2021-06-03 07:52 UTC, martincostello approved these changes

2021-06-03 07:52 UTC, martincostello commented on test/AspNet.Security.OAuth.Providers.Tests/Coinbase/CoinbaseTests.cs
> +        [Theory]
I'll add the test for this myself post-merge so I can get the next release shipped.

2021-06-03 07:57 UTC, merged

2021-06-03 14:27 UTC, levimatheri commented
@martincostello Thank you!

2021-06-03 22:23 UTC, levimatheri commented
@martincostello The request to Coinbase user profile needs to be a GET request. Sorry. Can I push a change to fix this?